#!/bin/sh

cat /dev/stdin | sed -r 's/\?|<u>|<\/u>//g' | tr [:upper:] [:lower:] | \
    tr '`' '\47' | \
    awk '/^ *<td[^>]*>(p|k|\47|m|n|w|l|h|a|e|i|o|u| )+<\57td> *$/ {print;}' | \
    awk '{gsub(/^ *<td[^>]*>/, ""); gsub(/<\57td> *$/, ""); print;}' | \
    awk '{for(i = 1; i <= NF; i++) {print $i;}}' | sort -u
