#!/bin/sh

IFS=$'\n'

# Test basic poornames
actual_output=`./poornames testdir`
expected_output='testdir/-file
testdir/..profile
testdir/.abababababababa
testdir/.profile
testdir/St._Andrews
testdir/St._Andrews2
testdir/abababababababa
testdir/f ile
testdir/f*ile
testdir/file0
testdir/hAlloween/
testdir/hallOween
testdir/halloween/
testdir/libstdc++.so.6
testdir/st._anDrEWS
testdir/st._anDrEWS2'

if [ "$actual_output" = "$expected_output" ]
then
    echo "basic poornames: PASS"
else
    echo "basic poornames: FAIL"
fi

# Test recursive poornames
ractual_output=`./poornames -r d`
# TODO: make sure order correct
rexpected_output='d/a/B/
d/a/C
d/a/b/
d/a/c/
d/A/
d/a/'

if [ "$ractual_output" = "$rexpected_output" ]
then
    echo "recursive poornames: PASS"
else
    echo "recursive poornames: FAIL"
fi
